language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - 2.0.0
  - 2.1.0
  - rbx-2.1.1
  - jruby-18mode
  - jruby-19mode
  - ree
script: bundle exec rspec
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ree
